modLoader="javafml" 
loaderVersion="[36,)" 
license="All rights reserved"

[[mods]]
modId="revsbetterstructures"
version="1.4" 
displayName="Rev's Better Structures" 
description='''
Rev's Better structures add new and refreshed structures to Minecraft!
'''

[[dependencies.revsbetterstructures]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.revsbetterstructures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"